/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


function get_list_fibonacci_under(max) {
    var list = [1, 2];
    var a = 1, b = 2;
    var c = a + b;
    while (c < max) {
        list.push(c);
        a = b;
        b = c;
        c = a + b;
    }
    return list;
}

function main(max) {
    var sum = 0;
    var list_fibo = get_list_fibonacci_under(max);
    for (var i = 0; i < list_fibo.length; i++) {
        if (list_fibo[i] % 2 === 0) {
            sum += list_fibo[i];
        }
    }
    return sum;
}


console.log(main(4e6));
// 4613732
